name: shop_shop
description: A modern Flutter mobile shop app for selling trendy shoes with Firebase integration.
version: 1.0.1+2
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  animated_background: ^2.0.0
  http: ^1.2.1
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  google_sign_in: ^5.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.0.0 # Thêm dòng này
  flutter_localizations: # Thêm để hỗ trợ đa ngôn ngữ
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/logo1.png
    - assets/logo2.png