name: shop_shop
description: A modern Flutter mobile shop app for selling trendy shoes with Firebase integration.
version: 1.0.1+2
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.3
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  animated_background: ^2.0.0
  http: ^1.2.1
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  google_sign_in: ^6.1.0
  shared_preferences: ^2.2.2
  firebase_messaging: ^15.2.8
  path_provider: ^2.1.3
  fluttertoast: ^8.2.2
  flutter_slidable: ^3.0.0
  universal_html: ^2.0.8
  uni_links: ^0.5.1
  url_launcher: ^6.3.0  # Thêm để mở ứng dụng ZaloPay
  uuid: ^4.5.0  # Thêm để tạo UUID
  crypto: ^3.0.5  # Đã có trong http, nhưng kiểm tra cho chắc
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/logo1.png
    - assets/logo2.png