// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXFikc1i14_x0xMfwY1Aqi9QsdglhviDc',
    appId: '1:820470788279:web:c6e72c1eba22caa5ab5d32',
    messagingSenderId: '820470788279',
    projectId: 'shoe-shop-flutter',
    authDomain: 'shoe-shop-flutter.firebaseapp.com',
    storageBucket: 'shoe-shop-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLW3VkrywUn9_GeVeNjJ-PS75m-vBco8o',
    appId: '1:820470788279:android:e30393cbda5b7a0eab5d32',
    messagingSenderId: '820470788279',
    projectId: 'shoe-shop-flutter',
    storageBucket: 'shoe-shop-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWEza5UnhKHGmS0i1jnvsAhnnXUiLBN78',
    appId: '1:820470788279:ios:ee5e31e1f5a88c33ab5d32',
    messagingSenderId: '820470788279',
    projectId: 'shoe-shop-flutter',
    storageBucket: 'shoe-shop-flutter.firebasestorage.app',
    iosBundleId: 'com.example.shopShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWEza5UnhKHGmS0i1jnvsAhnnXUiLBN78',
    appId: '1:820470788279:ios:ee5e31e1f5a88c33ab5d32',
    messagingSenderId: '820470788279',
    projectId: 'shoe-shop-flutter',
    storageBucket: 'shoe-shop-flutter.firebasestorage.app',
    iosBundleId: 'com.example.shopShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXFikc1i14_x0xMfwY1Aqi9QsdglhviDc',
    appId: '1:820470788279:web:471582353b16eb83ab5d32',
    messagingSenderId: '820470788279',
    projectId: 'shoe-shop-flutter',
    authDomain: 'shoe-shop-flutter.firebaseapp.com',
    storageBucket: 'shoe-shop-flutter.firebasestorage.app',
  );
}
